#!/usr/bin/python3
'''
	Factorize as many numbers as possible into a product of two smaller numbers.

	Usage: factors <file>
	where <file> is a file containing natural numbers to factor.
	One number per line
	You can assume that all lines will be valid natural numbers greater than 1
	You can assume that there will be no empy line, and no space before and after the valid number
	The file will always end with a new line
	Output format: n=p*q
	one factorization per line
	p and q don’t have to be prime numbers
	See example
	You can work on the numbers of the file in the order of your choice
	Your program should run without any dependency: You will not be able to install anything on the machine we will run your program on
	Time limit: Your program will be killed after 5 seconds if it hasn’t finish
	Push all your scripts, source code, etc… to your repository
	we will only run your executable factors
'''
import sys

f = open(sys.argv[1], 'r')

lines = f.readlines()

for line in lines:
    if line:
        var = int(line.strip())
        if var % 2 == 0:
            print("{}={}*{}".format(var, var // 2, 2))
            continue
        for mod in range(3, var, 2):
            if var % mod == 0:
                print("{}={}*{}".format(var, var // mod, mod))
                break
