#!/usr/bin/python3
import sys

f = open(sys.argv[1], 'r')

lines = f.readlines()

for line in lines:
    if line:
        var = int(line.strip())
        if var % 2 == 0:
            print("{}={}*{}".format(var, var // 2, 2))
            continue
        for mod in range(3, var, 2):
            if var % mod == 0:
                print("{}={}*{}".format(var, var // mod, mod))
                break
